name: Build & Deploy Docker to Proxmox VM

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_NAME: jaafarhadeg/sasalm

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate image tag
        id: meta
        run: echo "TAG=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t "${IMAGE_NAME}:${{ steps.meta.outputs.TAG }}" -t "${IMAGE_NAME}:latest" .

      - name: Push Docker image
        run: |
          docker push "${IMAGE_NAME}:${{ steps.meta.outputs.TAG }}"
          docker push "${IMAGE_NAME}:latest"

      - name: Deploy on Proxmox VM (pull & restart)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 135.125.4.184
          username: tython
          port: 6419
          key: ${{ secrets.VM_SSH_KEY }}
          envs: IMAGE_NAME
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker pull "${IMAGE_NAME}:latest"
            docker stop sasalm || true
            docker rm sasalm || true
            docker run -d --name sasalm -p 80:80 "${IMAGE_NAME}:latest"
